server:
  port: 9081
spring:
  cloud: 
      config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/SEBASJO26/microserv
          search-paths: config-data
  application:
    name: config-service